# Generated by Django 2.2.6 on 2019-10-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_in',
            field=models.DateField(verbose_name='Date In'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_out',
            field=models.DateField(verbose_name='Date Out'),
        ),
        migrations.CreateModel(
            name='OccupiedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check In')),
                ('check_out', models.DateField(verbose_name='Check Out')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Room')),
            ],
        ),
    ]
