# Generated by Django 2.2.6 on 2019-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191028_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_number',
            field=models.IntegerField(default=1, verbose_name='Number of guests'),
        ),
    ]
